### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by jonasnobile** [open-source-labs/SvelteStorm#52]
### Describe the bug
Not working `npm install` on MacBook with M1 chip. Is there a reason to use Electron v8? Electron >= v11 has separate arm64 build.

### Logs

``` zsh
npm ERR! code 1
npm ERR! path /Users/nebula/Git/SvelteStorm/node_modules/electron-chromedriver
npm ERR! command failed
npm ERR! command sh -c node ./download-chromedriver.js
npm ERR! /Users/nebula/Git/SvelteStorm/node_modules/electron-chromedriver/download-chromedriver.js:19
npm ERR!   if (err != null) throw err
npm ERR!                    ^
npm ERR! 
npm ERR! Error: Failed to find Electron v8.0.0 for darwin-arm64 at https://github.com/electron/electron/releases/download/v8.0.0/chromedriver-v8.0.0-darwin-arm64.zip
npm ERR!     at Request.<anonymous> (/Users/nebula/Git/SvelteStorm/node_modules/nugget/index.js:169:61)
npm ERR!     at Request.emit (node:events:394:28)
npm ERR!     at Request.onRequestResponse (/Users/nebula/Git/SvelteStorm/node_modules/request/request.js:1059:10)
npm ERR!     at ClientRequest.emit (node:events:394:28)
npm ERR!     at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:621:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:127:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:487:22)
npm ERR!     at TLSSocket.emit (node:events:394:28)
npm ERR!     at addChunk (node:internal/streams/readable:312:12)
npm ERR!     at readableAddChunk (node:internal/streams/readable:287:9)
```

**Comment by samfilip** [comment]
The only reason we are using Electron 8 is because that's what we were able to get up and running quickly. We have a seperate issue to bump all dependencies to the latest version and is in progress on other branches. Please feel free to bump electron locally and make a PR if stable :)
