### ISSUE TITLE
npm start error

### ISSUE THREAD

**Issue by sahinmansuroglu** [open-source-labs/SvelteStorm#53]
When I run npm start get :

D:\SVELTE\SvelteStorm-main>npm start

> svelte-storm@1.0.0 start D:\SVELTE\SvelteStorm-main
> concurrently "npm:svelte-dev" "electron-forge start"

[svelte-dev]
[svelte-dev] > svelte-storm@1.0.0 svelte-dev D:\SVELTE\SvelteStorm-main
[svelte-dev] > rollup -c -w
[svelte-dev]
[1] - Checking your system
[svelte-dev] rollup v2.53.2
[svelte-dev] bundles src/svelte.js → public...
[1] √ Checking your system
[1] - Locating Application
[1] √ Locating Application
[1] - Preparing native dependencies
[1] √ Preparing native dependencies
[1] - Launching Application
[1] √ Launching Application
[1]
[1] App threw an error during load
[1] Error: Cannot find module 'node-pty'
[1] Require stack:
[1] - D:\SVELTE\SvelteStorm-main\src\index.js
[1] - D:\SVELTE\SvelteStorm-main\node_modules\electron\dist\resources\default_app.asar\main.js
[1] -
[1]     at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
[1]     at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
[1]     at Module._load (internal/modules/cjs/loader.js:691:27)
[1]     at Function.Module._load (electron/js2c/asar.js:748:26)
[1]     at Module.require (internal/modules/cjs/loader.js:853:19)
[1]     at require (internal/modules/cjs/helpers.js:74:18)
[1]     at Object.<anonymous> (D:\SVELTE\SvelteStorm-main\src\index.js:6:13)
[1]     at Module._compile (internal/modules/cjs/loader.js:968:30)
[1]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[1]     at Module.load (internal/modules/cjs/loader.js:816:32)
[svelte-dev] A plugin is directly adding properties to the bundle object in the "generateBundle" hook. This is deprecated and will be removed in a future Rollup version, please use "this.emitFile" instead.
[svelte-dev] created public in 15.4s

**Comment by samfilip** [comment]
Did you try manually installing node-pty@0.10.1?

**Comment by trasherdk** [comment]
Also, the build/installed version have some problems. It does start, and seems functional, when dismissing the error dialog, on Windows 8.1 (x64)
```
$ git version
git version 2.32.0.windows.2

$ node -v && npm -v
v14.17.3
7.19.1
```

```
admin@ACER-64BIT MINGW64 /c/Apps/Development/Svelte/svelte-storm-win32-ia32
$ ./svelte-storm.exe
```
![image](https://user-images.githubusercontent.com/5003891/126106005-49a4daba-50a1-4d38-ad14-4171f5d0836c.png)

**Comment by NesTar6** [comment]
Hi the Javascript Error in main process is being addressed in a seperate issue thread. Unless there's anything else I'm closing this issue. Please open another if there's anything else.
