### ISSUE TITLE
update installation instructions

### ISSUE THREAD

**Issue by manuel3108** [open-source-labs/SvelteStorm#57]
I just checked out the repo, and got the following error on `npm i`

<details>
  <summary>npm i log</summary>
  
```
D:\Privat\SvelteStorm>npm i
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated rollup-plugin-json@4.0.0: This module has been deprecated and is no longer maintained. Please use @rollup/plugin-json.
npm WARN deprecated rollup-plugin-replace@2.2.0: This module has moved and is now available at @rollup/plugin-replace. Please update your dependencies. This version is no longer maintained.
npm WARN deprecated babel@6.23.0: In 6.x, the babel package has been deprecated in favor of babel-cli. Check https://opencollective.com/babel to support the Babel maintainers
npm WARN deprecated webdriverio@4.14.4: outdated version, please use @next
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path D:\Privat\SvelteStorm\node_modules\node-pty
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/install.js
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.2.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.5 found at "C:\Users\mserret\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.2.0/node-v16.2.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.2.0/node-v16.2.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.2.0/SHASUMS256.txt
npm ERR! gyp http GET https://nodejs.org/download/release/v16.2.0/win-x86/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.2.0/win-x64/node.lib
npm ERR! gyp http GET https://nodejs.org/download/release/v16.2.0/win-arm64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.2.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.2.0/win-x64/node.lib
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.2.0/win-x86/node.lib
npm ERR! gyp http 404 https://nodejs.org/download/release/v16.2.0/win-arm64/node.lib
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS unknown version "undefined" found at "C:\Program Files\Microsoft Visual Studio\2022\Preview"
npm ERR! gyp ERR! find VS checking VS2019 (16.9.31205.134) found at:
npm ERR! gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise"
npm ERR! gyp ERR! find VS - "Visual Studio C++ core features" missing
npm ERR! gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (D:\Privat\SvelteStorm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
npm ERR! gyp ERR! stack     at D:\Privat\SvelteStorm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (D:\Privat\SvelteStorm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
npm ERR! gyp ERR! stack     at D:\Privat\SvelteStorm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
npm ERR! gyp ERR! stack     at D:\Privat\SvelteStorm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
npm ERR! gyp ERR! stack     at D:\Privat\SvelteStorm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at D:\Privat\SvelteStorm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\Privat\\SvelteStorm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd D:\Privat\SvelteStorm\node_modules\node-pty
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mserret\AppData\Local\npm-cache\_logs\2021-07-20T08_33_54_179Z-debug.log
```
</details>

So apparently there are some dependencies that need to be setup before running `npm i`. Especially some VS stuff, that i don't want to have on my compiter :D

**Suggestion:**
Add those details to the Readme.

**Comment by NesTar6** [comment]
Hi, 

Were you using Visual Studio or VS Code?

**Comment by manuel3108** [comment]
I used the windows terminal. I only have VS Code installed. Apparently you need to have VS installed in order to build this.

**Comment by NesTar6** [comment]
This was built in VS Code, there should be no need for Visual Studio to build or run Svelte Storm. Try opening it in VS code and using the terminal there.

**Comment by trasherdk** [comment]
Yes, to build windows applications, you will need a compiler and some libraries/runtime stuff. No big surprise there.

A notice in the `README` about exactly what those requirements are might be helpful.

I have `Visual Studio 2017 (Express)` installed, but not exactly updated, and the build succeeded.

**Comment by manuel3108** [comment]
Running it from VS Code did not change anything.

But later I noticed that the computer i was trying to install already had VS installed (2017 Enterprise, 2019 Enterprise, 2022 Enterprise Preview), also setup to do some ASP.Net C# development. 

I needed to check this box and install the new things in the VS Installer: 
![image](https://user-images.githubusercontent.com/30698007/126603136-ab03f9c6-e59f-45e9-b875-fcc5a1c16796.png)
Those dependencies seem to be necessary for Electron builds.

**Comment by NesTar6** [comment]
Hi, looks like you got everything settled. Closing this issue. If another problem occurs please let us know.

**Comment by manuel3108** [comment]
Well if you feel to close this feel free. I think the better way would be to add a description to the readme before the `npm i`. Most people working on nodejs propably don't have VS and especially the VS C++ Extension installed. Or at least link the issue in the readme.

But thats not up to me!

**Comment by NesTar6** [comment]
Good point! Added link to issue in the readme
